### ISSUE TITLE
Repeat elements fails

### ISSUE THREAD

**Issue by martindevans** [martindevans/BeautifulBlueprints#7]
This very basic layout fails:

```
!Repeat
Orientation: Vertical
MinimizeRepeats: false
Children:
  - !Space
    PreferredWidth: 10000
    PreferredHeight: 10000
```
