### ISSUE TITLE
Layout Fail

### ISSUE THREAD

**Issue by martindevans** [martindevans/BeautifulBlueprints#8]
The following layout fails at various sizes, for example:

Width: 601
Height: 200

```
!Repeat
Children:
  - !AspectRatio
    MinWidth: 100
    MaxHeight: 200
    PreferredWidth: 75
    Ratio: 0.75
```
